apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
  labels:
    app: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: hajeongcheol/course:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/courses'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/courses'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5