apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  labels:
    app: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
        - name: class
          image: hajeongcheol/class:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/classes'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/classes'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5